### ISSUE TITLE
[Crash Issue] 경로 탐색 (findPathData) addPolyLine Crash

### ISSUE THREAD

**Issue by jw-choi-hyundai** [PlayMap-HMNS/Playmap-developers#10]
- mMapRestApi.findPathData를 못가져와서 polyLine 이 null이여서 발생한 crash로 보입니다. (그래도 예외처리 필요해보입니다.)

- PlayMapRestApi에서 아래와 같이 jsonArray가 null로 떨어집니다.
 jsonArray = getDownloadFromPostUrlArray("findPathData", uri.toString(), contents.toString(), true);
    

**[소스]**
```

private void testfindPathData()
    {
        new Thread() {
            @Override
            public void run() {
                PlayMapPoint point1 = mGpsTracker.getCurrentPlayMapPoint();
                PlayMapPoint point2 = randomHMNSPoint();
                PlayMapMarker mapMarker1 = new PlayMapMarker();
                PlayMapMarker mapMarker2 = new PlayMapMarker();
                mapMarker1.setMapPoint(point1);
                mapMarker2.setMapPoint(point2);
                mapMarker1.setIcon(BitmapFactory.decodeResource(getResources(), R.drawable.ic_start));
                mapMarker2.setIcon(BitmapFactory.decodeResource(getResources(), R.drawable.ic_end));
                try {
                    **PlayMapPolyLine polyLine = mMapRestApi.findPathData("0", "0", "0", "2", point1, point2);
                    mMapView.addPolyLine("routeResult", polyLine);**
                    mMapView.addMarkerItem("start", mapMarker1);
                    mMapView.addMarkerItem("end", mapMarker2);
                } catch (JSONException e) {
                    e.printStackTrace();
                }

            }
        }.start();
    }
```

**[로그]**
2020-11-25 16:25:35.330 14899-14983/com.playmap.playmapdev W/HMNS: --------- beginning of crash
2020-11-25 16:25:35.330 14899-14983/com.playmap.playmapdev E/AndroidRuntime: FATAL EXCEPTION: Thread-9
    Process: com.playmap.playmapdev, PID: 14899
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.hmns.playmap.shape.PlayMapPolyLine.setMapView(com.hmns.playmap.PlayMapView)' on a null object reference
        at com.hmns.playmap.PlayMapView.addPolyLine(PlayMapView.java:2372)
        at com.playmap.playmapdev.MapActivity$3.run(MapActivity.java:114)

**Comment by jw-choi-hyundai** [comment]
SDK용 key 값 변경시 정상적으로 표출

**Comment by Playmap-HAE** [comment]
안녕하세요. PlayMap입니다.

최근 인증방식의 변경으로 인하여 Android SDK 최신 버전이 금일 업로드 되었습니다.
번거로우시겠지만 최신 버전 SDK를 다시 다운로드 후 경로탐색 재시도 부탁드립니다.

1. Project > app > libs 파일 내 aar 파일을 붙여넣은 후 
2. build.gradle aar 파일명 변경

*참고 

dependencies {

    implementation 'com.facebook.soloader:soloader:0.6.0+'
    implementation name: 'PlayMapSDK_1.1', ext: 'aar'

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

3. Gradle Sync 
4. App Build

그리고 addPolyLine Crash 문제는 개발하시는 App 에서 
polyLine이 null아 아닌 경우 경우에만 addPolyLine 함수가 호출되도록 수정하면 발생하지 않을 것으로 예상됩니다.
다음 소스 참고 바랍니다.

if(polyLine != null) {
	mapView.addPolyLine("routeResult", polyLine);
	mapView.addMarkerItem("start", mapMarker1);
	mapView.addMarkerItem("end", mapMarker2);
}

감사합니다.

**Comment by jw-choi-hyundai** [comment]
감사합니다.
SDK 수정으로 close
