### ISSUE TITLE
[Exception Issue] POI 검색 시 JSON Exception 발생

### ISSUE THREAD

**Issue by jw-choi-hyundai** [PlayMap-HMNS/Playmap-developers#15]
아래와 같이 POI 검색 요청 시 JSON에서 title이 없는 경우도 있는지요?

[소스]
PlayMapPoiItem poiItem = mMapRestApi.findPOIDetailSearch(poiItems.get(i).poiId, 0);

[로그]
W/System.err: org.json.JSONException: No value for title
        at org.json.JSONObject.get(JSONObject.java:400)
W/System.err:     at org.json.JSONObject.getString(JSONObject.java:561)
        at com.hmns.playmap.network.PlayMapRestApi.findPOIDetailSearch(PlayMapRestApi.java:1776)
W/System.err:     at com.playmap.playmapdev.MapActivity$8.run(MapActivity.java:230)

**Comment by Playmap-HAE** [comment]
안녕하세요. PlayMap 입니다.

불편을 드려 죄송합니다. 
POI 상세 정보 검색 Response title은 필수값으로 
해당 오류가 발생한 Request 데이터를 전달해주시면 확인하도록 하겠습니다.

POI 상세 정보 검색 Api 정보
https://developers.hyundai-mnsoft.com/index.html#restapi/docs/poiDetail

감사합니다.

**Comment by jw-choi-hyundai** [comment]
엠엔소프트라고 입력시 POIdetailSearch 시 JSONException 발생됩니다.

[소스]
```
//poi리스트 get
ArrayList<PlayMapPoiItem> poiItems = mMapRestApi.findAllPOI(keyword, mGpsTracker.getCurrentPlayMapPoint().getLatitude(), mGpsTracker.getCurrentPlayMapPoint().getLongitude(), 1, "fts_poi", 0, 10, 3);
for (int i = 0; i < poiItems.size(); i++) {
   final PlayMapMarker mapMarker = new PlayMapMarker();
   mapMarker.setMapPoint(new PlayMapPoint(poiItems.get(i).centerLat, poiItems.get(i).centerLon));

    try {
//detailSearch 할 경우 JSONException no value for title 발생 (array 3번쨰로 추측 됩니다.)
  PlayMapPoiItem poiItem = mMapRestApi.findPOIDetailSearch(poiItems.get(i).poiId, 0);
  sID = key + i;
  mMapView.addMarkerItem(sID, mapMarker);
  mPOIItemMap.put(sID, poiItem);//추가 사항

   } catch (JSONException e) {
     continue;
   }
```

**Comment by Playmap-HAE** [comment]
안녕하세요. PlayMap입니다.

전달주신 키워드로 확인한 결과 SDK V1.0.1 가 검증계 Url로 확인되어
Android Rest Api Url 검증계 -> 운영계 변경 적용된 SDK를 업로드 하였습니다.
번거로우시겠지만  V1.0.2 SDK를 다운로드 후 재시도 부탁드립니다.
(V1.0.2 SDK 적용 후 Response Title 확인 하였습니다)

1. Project > app > libs 파일 내 aar 파일을 붙여넣은 후
2. build.gradle aar 파일명 변경
dependencies {

implementation 'com.facebook.soloader:soloader:0.6.0+'
implementation name: 'PlayMapSDK_1.2', ext: 'aar'

implementation 'androidx.appcompat:appcompat:1.2.0'
implementation 'com.google.android.material:material:1.2.1'
implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
testImplementation 'junit:junit:4.+'
androidTestImplementation 'androidx.test.ext:junit:1.1.2'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

3. Gradle Sync
4. App Build

감사합니다.

**Comment by jw-choi-hyundai** [comment]
v1.2 SDK test시에 정상적으로 동작하고 있습니다.
감사합니다.
