### ISSUE TITLE
[Q&A] 경로 탐색 JSON 파일에 대한 GUIDE 부탁드립니다.

### ISSUE THREAD

**Issue by jw-choi-hyundai** [PlayMap-HMNS/Playmap-developers#18]
[내용]
경로 탐색 시 상세 정보에 대한 JSON 파일을 얻어 올 수 있는데, site내에 따로 Guide가 있으면 좋을 것 같습니다.
JSON 파일에 상세 정보에 대한 Guide 부탁드립니다.

[DATA]
jsonObject = {JSONObject@17543} "{"PosList":[{"X":126.9653611,"Y":37.5305805,"index":0},{"X":126.9653611,"Y":37.5305805,"index":1},{"X":126.9657888,"Y":37.5308138,"index":2},{"X":126.9658138,"Y":37.530825,"index":3},{"X":126.9658444,"Y":37.5308277,"index":4},{"X":126.9658888,"Y":37.5308194,"index":5},{"X":126.9662222,"Y":37.5306694,"index":6},{"X":126.9662944,"Y":37.5305944,"index":7},{"X":126.9666472,"Y":37.5302916,"index":8},{"X":126.9666972,"Y":37.5302083,"index":9},{"X":126.9667833,"Y":37.5301138,"index":10},{"X":126.9668527,"Y":37.5300249,"index":11},{"X":126.9668555,"Y":37.5299861,"index":12},{"X":126.9668416,"Y":37.5299388,"index":13},{"X":126.9668,"Y":37.5298555,"index":14},{"X":126.9666805,"Y":37.5297388,"index":15},{"X":126.9666166,"Y":37.5296722,"index":16},{"X":126.9665666,"Y":37.5296111,"index":17},{"X":126.9664666,"Y":37.5294222,"index":18},{"X":126.9660638,"Y":37.5289777,"index":19},{"X":126.9657472,"Y":37.528625,"index":20},{"X":126.9651888,"Y":37.5279888,"index":21},{"X":126.9658388,"Y":37.5275972,"in"
 nameValuePairs = {LinkedHashMap@17624}  size = 5
  "PosList" -> {JSONArray@17634} "[{"X":126.9653611,"Y":37.5305805,"index":0},{"X":126.9653611,"Y":37.5305805,"index":1},{"X":126.9657888,"Y":37.5308138,"index":2},{"X":126.9658138,"Y":37.530825,"index":3},{"X":126.9658444,"Y":37.5308277,"index":4},{"X":126.9658888,"Y":37.5308194,"index":5},{"X":126.9662222,"Y":37.5306694,"index":6},{"X":126.9662944,"Y":37.5305944,"index":7},{"X":126.9666472,"Y":37.5302916,"index":8},{"X":126.9666972,"Y":37.5302083,"index":9},{"X":126.9667833,"Y":37.5301138,"index":10},{"X":126.9668527,"Y":37.5300249,"index":11},{"X":126.9668555,"Y":37.5299861,"index":12},{"X":126.9668416,"Y":37.5299388,"index":13},{"X":126.9668,"Y":37.5298555,"index":14},{"X":126.9666805,"Y":37.5297388,"index":15},{"X":126.9666166,"Y":37.5296722,"index":16},{"X":126.9665666,"Y":37.5296111,"index":17},{"X":126.9664666,"Y":37.5294222,"index":18},{"X":126.9660638,"Y":37.5289777,"index":19},{"X":126.9657472,"Y":37.528625,"index":20},{"X":126.9651888,"Y":37.5279888,"index":21},{"X":126.9658388,"Y":37.5275972,"index":22},{""
  "RgData" -> {JSONArray@17636} "[{"EndIdx":0,"PreTurn":0,"RgDistance":45,"RgTime":39,"Speed":0,"StartIndex":0,"TurnCODE":0,"TurnName":[{"Category":0,"Name":"출발지"},{"Category":4,"Name":"용산역북길"}]},{"EndIdx":1,"PreTurn":0,"RgDistance":449,"RgTime":196,"Speed":4,"StartIndex":1,"TurnCODE":2,"TurnName":[{"Category":1,"Name":"한강로"},{"Category":4,"Name":"용산역북길"}]},{"EndIdx":21,"PreTurn":0,"RgDistance":108,"RgTime":38,"Speed":8,"StartIndex":21,"TurnCODE":2},{"EndIdx":23,"PreTurn":0,"RgDistance":1739,"RgTime":283,"Speed":10,"StartIndex":23,"TurnCODE":3,"TurnName":[{"Category":1,"Name":"한강대로"},{"Category":4,"Name":"한강대로"}]},{"EndIdx":52,"PreTurn":0,"RgDistance":2373,"RgTime":174,"Speed":22,"StartIndex":52,"TurnCODE":3,"TurnName":[{"Category":1,"Name":"노들로"},{"Category":2,"Name":"양화대교"},{"Category":4,"Name":"노들로"}]},{"EndIdx":86,"PreTurn":0,"RgDistance":1205,"RgTime":92,"Speed":49,"StartIndex":86,"TurnCODE":4616,"TurnName":[{"Category":1,"Name":"영등포로터리"},{"Category":2,"Name":"양화대교"},{"Category":4,"Name":"노들로"},{"Category":5,"Nam"
  "RpOpt" -> {JSONObject@17638} "{"FeeOption":0,"RoadOption":0,"RouteOption":3}"
  "Summary" -> {JSONObject@17544} "{"TotalDistance":7944,"TotalFee":0,"TotalTime":1391}"
  "TraInfo" -> {JSONArray@17641} "[{"EndIndex":1,"RoadType":9,"Speed":29,"StartIndex":0,"TraLinkID":1089372},{"EndIndex":6,"RoadType":9,"Speed":29,"StartIndex":1,"TraLinkID":1089375},{"EndIndex":8,"RoadType":9,"Speed":29,"StartIndex":6,"TraLinkID":3846258},{"EndIndex":18,"RoadType":9,"Speed":29,"StartIndex":8,"TraLinkID":3938647},{"EndIndex":19,"RoadType":7,"Speed":13,"StartIndex":18,"TraLinkID":3938642},{"EndIndex":20,"RoadType":7,"Speed":13,"StartIndex":19,"TraLinkID":3938641},{"EndIndex":21,"RoadType":7,"Speed":12,"StartIndex":20,"TraLinkID":1092516},{"EndIndex":22,"RoadType":7,"Speed":25,"StartIndex":21,"TraLinkID":3969394},{"EndIndex":23,"RoadType":7,"Speed":20,"StartIndex":22,"TraLinkID":1090049},{"EndIndex":26,"RoadType":6,"Speed":43,"StartIndex":23,"TraLinkID":3969379},{"EndIndex":27,"RoadType":6,"Speed":20,"StartIndex":26,"TraLinkID":3793076},{"EndIndex":28,"RoadType":6,"Speed":20,"StartIndex":27,"TraLinkID":3793079},{"EndIndex":29,"RoadType":6,"Speed":20,"StartIndex":28,"TraLinkID":1047687},{"EndIndex":30,"Ro"

**Comment by Playmap-HAE** [comment]
안녕하세요. PlayMap 입니다.

경로탐색은 사이트 내 REST API > Docs > Directions 에서 확인 가능합니다.

경로탐색 url 
https://developers.hyundai-mnsoft.com/index.html#restapi/docs/routeSearch

감사합니다.

**Comment by jw-choi-hyundai** [comment]
REST API Docs로 확인 완료 

감사합니다.
