### ISSUE TITLE
마커가 찍힌 영역으로 이동 및 맵을 확대 하려고 합니다.

### ISSUE THREAD

**Issue by enjoymins1450** [PlayMap-HMNS/Playmap-developers#23]
안녕하세요.

webjs 로 개발 중입니다.

Marker나 MarkerClusterer 를 이용해 마커들을 찍은 후
마커가 모두 보일 수 있도록 위치 이동이나 줌으로 영역을 변경하고 싶은데 마땅한 API 가 없네요.
map.getExtent 로 영역을 받아 올 수 있는거 같은데.. 영역을 지정할 수가 없네요..
setCenter, setZoom으로 대략적으로 움직일 수 밖에 없는지
혹시 마땅한 방안이 있을지 답변 부탁합니다.

그리고 map.addMarkerLine 으로 라인들을 그리고 있는데..
map.clearMarker 로 10번에 2~3번쯤 지워지지 않고 남아 있는 경우가 있습니다.
버그 인건지... 사용 API 가 잘못된 건지 확실치 않네요..

어떻게 해야 될지 난감한 상황이라.
답변을 부탁 드리겠습니다.

감사합니다.

**Comment by Playmap-HAE** [comment]
안녕하세요 PlayMap 입니다.

현재 화면의 마커들의 전체영역을 계산하는 함수가 있습니다.
해당함수를 이용하여 아래와 같이 하시면 됩니다.
map.getView().fit(map.getMarkerExtent());

addMarkerLine은 좀 더 상세한 정보를 알려주시면 추가 확인해보겠습니다.

감사합니다.
